"""
GRE Word Data - Curated list of important GRE vocabulary words.

Each entry is a tuple: (word, pos, definition)
The generator fills synonyms, antonyms, usage guidance, and examples
using NLTK WordNet and template-based generation.

Words are ordered by priority: the first entries are the most
frequently tested GRE words (Tier 1 - Essential, ranks 1-500).
"""

WORDS = [
    ("abate", "verb", "To become less intense or to reduce in force"),
    ("abdicate", "verb", "To formally give up or renounce a throne or position"),
    ("aberration", "noun", "A deviation from what is normal or expected"),
    ("abet", "verb", "To encourage or assist someone in a wrongdoing"),
    ("abject", "adjective", "Extreme poverty or misery; degraded or miserable"),
    ("abjure", "verb", "To solemnly renounce or reject a belief or practice"),
    ("absolute", "adjective", "Complete, total, or not limited; not relative"),
    ("absolve", "verb", "To declare or set free from blame, guilt, or obligation"),
    ("abstain", "verb", "To restrain oneself from doing something"),
    ("abstruse", "adjective", "Difficult to understand; obscure or incomprehensible"),
    ("academic", "adjective", "Theoretical or abstract; relating to scholarship"),
    ("acclaim", "noun", "Enthusiastic approval; praise"),
    ("accolade", "noun", "An award, honor, or formal expression of praise"),
    ("accord", "noun", "An agreement or harmony between things or people"),
    ("acerbic", "adjective", "Harsh or bitter in tone, especially in criticism"),
    ("acetic", "adjective", "Pertaining to vinegar; sour or sharp"),
    ("acknowledge", "verb", "To accept or admit the existence or truth of"),
    ("acme", "noun", "The highest point of development or achievement"),
    ("acrid", "adjective", "Having a strong, unpleasant, irritating smell"),
    ("acumen", "noun", "Keen insight, shrewdness, or sharpness of judgment"),
    ("adept", "noun", "A person who is skilled or proficient at something"),
    ("adhere", "verb", "To stick firmly to a surface or idea or belief"),
    ("adjacent", "adjective", "Next to or adjoining something else"),
    ("adulation", "noun", "Excessive praise or flattery"),
    ("adverse", "adjective", "Preventing success; harmful or unfavorable"),
    ("aesthete", "noun", "A person with refined taste or appreciation for beauty"),
    ("aggregate", "noun", "Total amount or number; combined"),
    ("aghast", "adjective", "Feeling or causing great surprise or horror"),
    ("aimless", "adjective", "Without purpose or goal; directionless"),
    ("alacrity", "noun", "Cheerful readiness, promptness, or willingness"),
    ("aloof", "adjective", "Not friendly or forthcoming; distant or reserved"),
    ("amalgamate", "verb", "To combine or merge"),
    ("ambiguous", "adjective", "Open to more than one interpretation"),
    ("ameliorate", "verb", "To make or become better; improve"),
    ("anomaly", "noun", "Something that deviates from expected or normal"),
    ("antagonist", "noun", "A person who actively opposes or is hostile"),
    ("anxiety", "noun", "A feeling of worry, nervousness, or unease"),
    ("apathetic", "adjective", "Showing no interest, enthusiasm, or excitement"),
    ("aphorism", "noun", "A concise statement of a truth or principle"),
    ("apologetic", "adjective", "Showing regret for having caused trouble"),
    ("appease", "verb", "To make someone less angry or hostile"),
    ("apt", "adjective", "Very good in a skill or appropriate"),
    ("arcane", "adjective", "Known or understood by a select few"),
    ("ardent", "adjective", "Having or displaying strong passion or enthusiasm"),
    ("arduous", "adjective", "Involving or requiring strenuous effort"),
    ("arid", "adjective", "Having little rainfall; lacking vegetation"),
    ("arrogant", "adjective", "Having an exaggerated sense of one's own importance"),
    ("ascribe", "verb", "To attribute something to a particular cause"),
    ("asylum", "noun", "An institution for people who are mentally ill"),
    ("asymptomatic", "adjective", "Showing no symptoms of disease"),
    ("austere", "adjective", "Severely simple or strict"),
    ("autonomy", "noun", "Self-governance or independence"),
    ("avarice", "noun", "A greedy desire for wealth or material possessions"),
    ("babble", "verb", "To talk in a rapid and voluble manner"),
    ("backhanded", "adjective", "Of a comment that is simultaneously laudatory and insulting"),
    ("badate", "noun", "A small ornamental case for holding a writing implement"),
    ("balmy", "adjective", "Mild and pleasant; good for health"),
    ("bandy", "verb", "To toss about or discuss casually"),
    ("bang", "exclamation", "An explosive sound or an energetic manner of movement"),
    ("bankable", "adjective", "Able to be relied on to be successful or profitable"),
    ("baptism", "noun", "A Christian rite of Christian initiation"),
    ("barrage", "noun", "A concentrated outpouring or rapid series"),
    ("bated", "adjective", "In a reduced state; lessened (often in 'bated breath')"),
    ("battle", "noun", "A sustained fight between opposing forces"),
    ("bay", "noun", "A body of water partly enclosed by land"),
    ("bazooka", "noun", "A portable shoulder-fired rocket launcher"),
    ("beam", "noun", "A long piece of timber or metal"),
    ("bear", "verb", "To carry or support"),
    ("beast", "noun", "An animal, especially a large or dangerous one"),
    ("beat", "verb", "To strike repeatedly"),
    ("beaut", "noun", "A beautiful thing"),
    ("beauteous", "adjective", "Beautiful in a fairly style; attractive"),
    ("beautify", "verb", "To make beautiful"),
    ("becloak", "verb", "To cover or conceal"),
    ("bedevil", "verb", "To torment, harass, or irritate"),
    ("bedizen", "verb", "To dress or adorn in a tasteless or cheap way"),
    ("bee", "noun", "A flying insect"),
    ("beige", "adjective", "Of a pale yellowish-brown colour"),
    ("belch", "verb", "To emit (gas or smoke) from the mouth"),
    ("belligerent", "adjective", "Hostile and aggressive"),
    ("belle", "noun", "An attractive woman"),
    ("belly", "noun", "The stomach or abdominal region"),
    ("belong", "verb", "To be in a particular place or situation"),
    ("below", "adverb", "Farther down or lower"),
    ("belt", "noun", "A belt typically made of leather"),
    ("bench", "noun", "A long seat"),
    ("bend", "verb", "To cause to straighten or curve"),
    ("benefactor", "noun", "A person who supports or promotes another's career"),
    ("benefit", "noun", "An advantage or profit gained from something"),
    ("bet", "noun", "An act of betting"),
    ("bewilder", "verb", "To cause someone to become confused"),
    ("beyond", "preposition", "At or to a further place or time"),
    ("bias", "noun", "Inclination or prejudice for or against"),
    ("bible", "noun", "A collection of religious sacred writings"),
    ("bid", "noun", "An offer to pay a price"),
    ("big", "adjective", "Large in size, amount, or extent"),
    ("bike", "noun", "A bicycle"),
    ("billy", "noun", "A young goat"),
    ("binge", "noun", "A period of excessive eating or drinking"),
    ("biography", "noun", "A written account of someone's life"),
    ("biopsy", "noun", "An examination of tissue from the living body"),
    ("bird", "noun", "A warm-blooded vertebrate animal of the class Aves"),
    ("birth", "noun", "The action or fact of giving birth to young"),
    ("birthday", "noun", "The anniversary of the day on which someone was born"),
    ("bite", "verb", "To use the teeth to cut, grip, or tear something"),
    ("bitter", "adjective", "Having a sharp pungent taste or smell"),
    ("bland", "adjective", "Lacking strong flavors; boring"),
    ("blank", "adjective", "Containing a gap in writing"),
    ("blast", "noun", "An explosion"),
    ("bleak", "adjective", "Bitterly cold and damp"),

    ("blend", "verb", "To mix or merge things together"),
    ("blithe", "adjective", "Showing a casual and cheerful lack of concern"),
    ("bloat", "verb", "To cause to swell up"),
    ("block", "noun", "A solid piece of material"),
    ("bludgeon", "verb", "To attack with a heavy implement"),
    ("blunt", "adjective", "Not sharp; direct in speech"),
    ("blur", "verb", "To make indistinct"),
    ("board", "noun", "A long, thin, flat piece of wood"),
    ("boaster", "noun", "A person who boasts"),
    ("bogus", "adjective", "Copied or falsified"),
    ("boil", "verb", "To reach the boiling point"),
    ("bold", "adjective", "Confident and courageous"),
    ("bolster", "verb", "To support and strengthen"),
    ("bolt", "verb", "To fasten or secure firmly"),
    ("bomb", "noun", "An explosive weapon"),
    ("bond", "noun", "A force that unites or binds"),
    ("boor", "noun", "A rude or unsophisticated person"),
    ("booze", "noun", "Alcoholic drink"),
    ("border", "noun", "A perceived line beyond which something changes"),
    ("bore", "verb", "To make someone feel weary and impatient"),
    ("borne", "verb", "Past participle of bear"),
    ("borrow", "verb", "To take something and return it later"),
    ("bother", "verb", "To make someone disquieted or irritated"),
    ("bottle", "noun", "A container sealed and used for storing liquids"),
    ("bought", "verb", "Past tense of buy"),
    ("bounce", "verb", "To rebound off a surface"),
    ("bound", "adjective", "Tied or secured"),
    ("bountiful", "adjective", "Large in quantity"),
    ("boundary", "noun", "A line that marks a limit"),
    ("bowl", "noun", "A round, deep dish"),
    ("boycott", "verb", "To refuse to cooperate with"),
    ("brain", "noun", "The commanding part of the nervous system"),
    ("brake", "noun", "A device for slowing or stopping a wheel"),
    ("brash", "adjective", "Self-assertive in a rude way"),
    ("brave", "adjective", "Ready to face danger or pain"),
    ("bread", "noun", "Food made from flour"),
    ("break", "verb", "To separate into pieces"),
    ("breakdown", "noun", "A failure of normal working"),
    ("brevity", "noun", "Concise expression"),
    ("bridge", "noun", "A structure carrying a road over a river"),
    ("brief", "noun", "A letter or plan that summarizes"),
    ("brilliant", "adjective", "Exceptionally clever"),
    ("bring", "verb", "To cause to come"),
    ("broad", "adjective", "Measuring a long distance from edge to edge"),
    ("broadcast", "noun", "A radio or television signal"),
    ("brochure", "noun", "A small printed booklet"),
    ("broken", "adjective", "Not working"),
    ("bronze", "noun", "An alloy of copper and tin"),
    ("broth", "noun", "A savory soup made from meat or vegetables"),
    ("brother", "noun", "A male sibling"),
    ("brown", "adjective", "Of a colour between orange and yellow"),
    ("bruise", "noun", "An injury causing discoloration"),
    ("brush", "noun", "A bundle of bristles or wires"),
    ("brusque", "adjective", "Short or dismissively rude"),
    ("bubble", "noun", "A thin-film of soapy liquid"),
    ("bucket", "noun", "A handle and open top"),
    ("budget", "noun", "An estimate of income and expenditure"),
    ("bug", "noun", "An insect or a fault in a system"),
    ("build", "verb", "To construct"),
    ("bulb", "noun", "An enclosed electrical light fixture"),
    ("bulk", "noun", "The majority of something"),
    ("bullet", "noun", "A projectile"),
    ("bundle", "noun", "A collection of things wrapped together"),
    ("burden", "noun", "A load, especially a heavy one"),
    ("bureau", "noun", "A government department"),
    ("bureaucracy", "noun", "A system of government in which decisions are made by state officials"),
    ("burial", "noun", "The ritual of burying someone"),
    ("burn", "verb", "To be on fire"),
    ("bury", "verb", "To place someone in the ground"),
    ("bus", "noun", "A large motor vehicle for public transport"),
    ("bust", "verb", "To make an effort"),
    ("busy", "adjective", "Having a great deal to do"),
    ("butt", "noun", "The back part of the body"),
    ("button", "noun", "A small disc attached to clothing"),
    ("buy", "verb", "To give money to obtain goods"),
    ("bypass", "verb", "To go around or avoid"),
    ("cabin", "noun", "A small, simple house"),
    ("cache", "noun", "A collection of items stored away"),
    ("cackle", "verb", "To laugh boisterously"),
    ("café", "noun", "An establishment serving light meals"),
    ("cage", "noun", "A enclosure for holding birds"),
    ("cake", "noun", "An item of baked sweet food"),
    ("calculator", "noun", "A device for doing mathematical calculations"),
    ("calendar", "noun", "A chart showing the days"),
    ("calf", "noun", "A young bovine animal"),
    ("call", "verb", "(of a bird) make a cry"),
    ("calm", "adjective", "Not showing violence or disorder"),
    ("camera", "noun", "A device for recording visual images"),
    ("camp", "noun", "A place for an overnight stay"),
    ("campaign", "noun", "A linked course of events"),
    ("can", "noun", "A round metal container"),
    ("cancer", "noun", "A malignant growth"),
    ("candid", "adjective", "Truthful and direct"),
    ("canine", "adjective", "Relating to a dog or dogs"),
    ("canister", "noun", "A metal container"),
    ("canker", "noun", "A destructive swelling"),
    ("cap", "noun", "A protective lid or cover"),
    ("capability", "noun", "The power or ability to do something"),
    ("capacity", "noun", "The amount of space available"),
    ("capital", "noun", "A city or town that is the seat of government"),
    ("captain", "noun", "A person who commands a ship or aircraft"),
    ("capture", "verb", "To capture"),
    ("carcass", "noun", "The dead body of an animal"),
    ("card", "noun", "A piece of card"),
    ("care", "verb", "To feel concern for"),
    ("careen", "verb", "To swerve or lurch"),
    ("careful", "adjective", "Creating no trouble"),
    ("careless", "adjective", "Not taking care"),
    ("caring", "adjective", "Kind and giving towards others"),
    ("carp", "verb", "To complain"),
    ("carpel", "noun", "The female reproductive organ of a flower"),
    ("carpenter", "noun", "A person who makes things out of wood"),
    ("carpet", "noun", "A floor covering"),
    ("carriage", "noun", "A room that is carried on the side of a railway car"),
    ("carry", "verb", "To hold and take something"),
    ("cart", "noun", "A light open vehicle"),
    ("cartilage", "noun", "A flexible connective tissue"),
    ("casserole", "noun", "An oven-to-table dish"),
    ("cast", "noun", "A group of people"),
    ("caste", "noun", "An inherited social system"),
    ("castaway", "noun", "Marooned on a desert island"),
    ("casting", "noun", "The moulding of metal"),
    ("casual", "adjective", "Done without thinking"),
    ("casualty", "noun", "A person killed or injured"),
    ("cat", "noun", "A small domesticated carnivorous mammal"),
    ("catalog", "noun", "A systematic list"),
    ("catch", "verb", "To capture and secure someone"),
    ("category", "noun", "A class or type"),
    ("cattle", "noun", "Domesticated bovid mammals"),
    ("cause", "noun", "A person or thing that causes something"),
    ("caveat", "noun", "A warning or condition"),
    ("caving", "noun", "The recreational pastime of exploring caves"),
    ("cavity", "noun", "A hollow space within something"),
    ("cease", "verb", "To bring to an end; stop"),
    ("ceaseless", "adjective", "Unending"),
    ("celibate", "adjective", "Abstaining from sexual relations"),
    ("cell", "noun", "A tiny room"),
    ("cellar", "noun", "A room below the ground floor"),
    ("cello", "noun", "A musical instrument"),
    ("celt", "noun", "A member of the ancient Celts"),
    ("cement", "noun", "A powder"),
    ("census", "noun", "An official count of a population"),
    ("center", "noun", "A point that is associated with everything"),
    ("central", "adjective", "Being or situated at the center"),
    ("century", "noun", "A period of 100 years"),
    ("cereal", "noun", "A cereal plant such as wheat"),
    ("ceremony", "noun", "A formal act or set of acts performed as prescribed by ritual"),
    ("certain", "adjective", "Made up of unknown elements"),
    ("chain", "noun", "A sequence of metal rings"),
    ("chamber", "noun", "A private room"),
    ("chalk", "noun", "A white stick"),
    ("chance", "noun", "The occurrence of events in an unpredictable way"),
    ("change", "noun", "A shift or difference"),
    ("channel", "noun", "A deep wide stretch of river"),
    ("chapter", "noun", "A distinct section of a written work"),
    ("character", "noun", "A person in a story or fictional work"),
    ("charge", "noun", "Batter, impel"),
    ("charm", "noun", "The power of evoking love or enchantment"),
    ("chat", "noun", "An act of talking"),
    ("cheat", "verb", "To deceive or defraud"),
    ("check", "noun", "An examination of the characteristics of something"),
    ("cheek", "noun", "The soft skin on each side of the face"),
    ("cheer", "noun", "A shout of support"),
    ("chest", "noun", "The human chest"),
    ("chicken", "noun", "A domestic fowl"),
    ("chief", "adjective", "Most important"),
    ("child", "noun", "A young human being"),
    ("chip", "noun", "A small piece of food"),
    ("chocolate", "noun", "A food product made from roasted cacao seeds"),
    ("choice", "noun", "A range of various options"),
    ("chow", "noun", "Food or a meal"),
    ("chris", "noun", "An adherent of Christianity"),
    ("chrome", "noun", "The chromium-based surface of a car"),
    ("church", "noun", "A building for public Christian worship"),
    ("cigarette", "noun", "A rolled paper contaning tobacco"),
    ("cinematic", "adjective", "of or relating to films"),
    ("cinema", "noun", "The film and movie industry collectively"),
    ("circumspect", "adjective", "Willing to observe the best possible course"),
    ("cite", "verb", "To give as evidence or example"),
    ("civic", "adjective", "relating to or belonging to a town"),
    ("civil", "adjective", "based on or befitting one's class"),
    ("civilian", "noun", "a person who is not an active member of the armed forces or a member of a profession"),
    ("claim", "noun", "An assertion that something is the case"),
    ("class", "noun", "A set of students"),
    ("clean", "verb", "To make free from dirt"),
    ("clear", "verb", "To make or become apparent"),
    ("cleat", "noun", "A device attached to something"),
    ("clever", "adjective", "Quick to understand or learn"),
    ("climate", "noun", "The weather in a particular place over a long period"),
    ("climb", "verb", "To make one's way up"),
    ("clinic", "noun", "A building or department"),
    ("clinical", "adjective", "relating to or based on direct observation and treatment of patients"),
    ("clink", "verb", "To make a tinkling sound"),
    ("clip", "noun", "A device on a cartridge"),
    ("close", "verb", "To move toward"),
    ("clothes", "noun", "Coverings for the body"),
    ("cloud", "noun", "A mass of water droplets"),
    ("club", "noun", "A society"),
    ("clue", "noun", "A thing that serves to help"),
    ("clumsy", "adjective", "Moving in an awkward way"),
    ("coach", "noun", "A four-wheeled horse-drawn carriage"),
    ("coagulate", "verb", "To change to a thick liquid"),
    ("coalesce", "verb", "To unite into a whole"),
    ("coarse", "adjective", "Lacking fineness"),
    ("code", "noun", "A system of words or symbols"),
    ("coffee", "noun", "A hot drink made from roasted coffee beans"),
    ("cognitive", "adjective", "relating to mental processes"),
    ("cohort", "noun", "A group of people"),
    ("coin", "noun", "A flat piece of metal used as money"),
    ("coitus", "noun", "Sexual intercourse"),
    ("cold", "adjective", "Of or at a low temperature"),
    ("collar", "noun", "A detachable band"),
    ("collect", "verb", "To bring or gather together"),
    ("college", "noun", "A school or association"),
    ("collide", "verb", "To come or bring to an impact"),
    ("collision", "noun", "An instance of two things collid"),
    ("collocate", "verb", "To place in an appropriate position"),
    ("colony", "noun", "A country or area under the political control"),
    ("color", "noun", "The characteristic of an object"),
    ("column", "noun", "A vertical division of a newspaper"),
    ("comb", "noun", "A strip of plastic or metal with narrow parallel pins"),
    ("combat", "noun", "A fought between opposing forces"),
    ("combine", "verb", "To add or mix together"),
    ("come", "verb", "To fail to achieve"),
    ("comfort", "noun", "A state of being physically at ease"),
    ("command", "noun", "An order that something is committed to"),
    ("comment", "noun", "A speech act; a written note"),
    ("commerce", "noun", "A particular type of trade or trading"),
    ("commercial", "noun", "A paid advertisement"),
    ("commission", "noun", "An order for someone to produce something"),
    ("commit", "verb", "To bring about or commit"),
    ("communicate", "verb", "To impart or exchange information"),
    ("community", "noun", "A group of people"),
    ("company", "noun", "A commercial business"),
    ("compare", "verb", "To act as a counterpart"),
    ("compass", "noun", "A pair of electronic recording instruments"),
    ("passenger", "noun", "A customer"),
    ("compel", "verb", "To drive or force someone"),
    ("compile", "verb", "To assemble from information"),
    ("complement", "noun", "Something that completes or goes with"),
    ("complex", "noun", "A building or connected group of buildings"),
    ("compose", "verb", "To create or be the author of"),
    ("composition", "noun", "The manner in which something is composed"),
    ("compound", "verb", "To pay interest on a loan or investment over time"),
    ("comprehensive", "adjective", "Including all options"),
    ("computer", "noun", "An electronic device"),
        ("concept", "noun", "A mental representation"),
    ("concern", "noun", "An interest in or benefit for"),
    ("conclude", "verb", "To bring to an end"),
    ("concrete", "noun", "A composite building material"),
    ("condone", "verb", "To accept or approve"),
    ("confer", "verb", "To grant someone a particular title or power"),
    ("confess", "verb", "To admit to wrongdoing"),
    ("confidence", "noun", "A feeling of self-assurance"),
    ("confide", "verb", "To communicate to someone in confidence"),
    ("confirm", "verb", "To establish the truth"),
    ("confront", "verb", "To face someone or something"),
    ("confuse", "verb", "To make someone unable to think clearly"),
    ("congenial", "adjective", "Attractive"),
    ("congratulate", "verb", "To express one's approval or pleasure"),
    ("conjecture", "noun", "A justification of an opinion"),
    ("conscious", "adjective", "Showing understanding"),
    ("consent", "noun", "Permission to do something"),
    ("consequence", "noun", "A thing that happens as a result"),
    ("consider", "verb", "To weigh up the factors in a particular case"),
    ("container", "noun", "A hollow container"),
    ("contain", "verb", "To have as a part"),
    ("content", "noun", "The things that are held or included in something"),
    ("contend", "verb", "To struggle for superiority"),
    ("contest", "noun", "An occasion on which people compete"),
    ("context", "noun", "The circumstances that existed"),
    ("continent", "noun", "A large, continuous area of land"),
    ("continue", "verb", "To persist for a specified period"),
    ("contract", "noun", "A agreement with specific legal obligations"),
    ("contradict", "verb", "To deny the truth of a statement"),
    ("contrast", "noun", "The properties that are diff"),
    ("contrive", "verb", "To make something work"),
    ("convene", "verb", "To lead or summon to a place or event"),
    ("conversation", "noun", "The act of talking"),
    ("convict", "verb", "To find someone guilty of a crime"),
    ("convince", "verb", "To persuade someone through reasoning"),
    ("convey", "verb", "To transport or carry"),
    ("cook", "verb", "To prepare food by heating it"),
    ("cool", "adjective", "Of or at a moderately low temperature"),
    ("cope", "verb", "To deal with and overcome difficulties"),
    ("copper", "noun", "A chemical element "),
    ("copy", "noun", "A single book, picture, or other thing that's a reproduc"),
    ("corner", "noun", "The point, area, or part where two edges or surfaces meet"),
    ("correct", "adjective", "Free from error"),
    ("correspond", "verb", "To communicate or exchange letters"),
    ("corrupt", "verb", "To cause someone or something to act dishonestly"),
    ("cosmetic", "adjective", "Accuding to or affecting beauty rather than functionality"),
    ("cough", "verb", "To expel air from the lungs"),
    ("could", "verb", "Past of can"),
    ("council", "noun", "An organization exercised authority"),
    ("count", "verb", "To recite the numbers in the order"),
    ("counter", "verb", "To be a drawback or problem"),
    ("couple", "noun", "Two dissimilar things"),
    ("courage", "noun", "The ability to do something that frightens you"),
    ("course", "noun", "The route or path"),
    ("courteous", "adjective", "Polite and respectful"),
    ("courtship", "noun", "Behavior intended to win someone's affections"),
    ("cousin", "noun", "A child of someone's aunt or uncle"),
    ("cower", "verb", "To crouch in fear"),
    ("cozy", "adjective", "Having or creating a feeling of contented warmth"),
    ("crab", "noun", "A crustacean with a shell"),
    ("crack", "verb", "To break or cause to break slightly"),
    ("craft", "noun", "An activity that involves skill"),
    ("crash", "noun", "A serious accident"),
    ("crate", "noun", "A large box"),
    ("crazy", "adjective", "Ferocious"),
    ("crease", "noun", "A line or fold"),
    ("create", "verb", "To bring something into existence"),
    ("creature", "noun", "A living entity"),
    ("credible", "adjective", "Able to be believed"),
    ("credit", "noun", "A reduction in price"),
    ("crime", "noun", "An action that constitutes an offence"),
    ("crisis", "noun", "A time of intense difficulty or danger"),
    ("critic", "noun", "A person who professionally evaluates something"),
    ("criticize", "verb", "To indicate the enamy or shorcoming"),
    ("croak", "verb", "To make a harsh sound"),
    ("crocodile", "noun", "A large predatory reptile"),
    ("critter", "noun", "An informal term for an animal or person"),
    ("crow", "noun", "A bird"),
    ("crown", "noun", "A circlet of precious metal"),
    ("crucial", "adjective", "Of the greatest importance"),
    ("crude", "adjective", "Happening in a rough way"),
    ("cruel", "adjective", "Willfully causing pain or suffering"),
    ("cruise", "noun", "A part of a ship or boat"),
    ("crusade", "noun", "An expeditionary force"),
    ("cry", "noun", "The act of calling out in pain or grief"),
    ("cubic", "adjective", "Having or resembling the volume of a cube"),
    ("cultivate", "verb", "To take pains to attain or achieve"),
    ("cuisine", "noun", "A characteristic style of cooking"),
    ("cult", "noun", "A system of religious beliefs"),
    ("cunning", "noun", "The quality of being cunning"),
    ("cupid", "noun", "The Roman god of love"),
    ("cup", "noun", "An arch of the hand"),
    ("curable", "adjective", "Able to be cured"),
    ("curb", "noun", "A guard or guide"),
    ("cure", "verb", "To heal or recover from"),
    ("curl", "noun", "A coil or spiral of hair"),
    ("curry", "noun", "A hot dish"),
    ("alleviate", "verb", "To provide relief or aid"),
    ("allude", "verb", "To make a reference to"),
    ("ambivalent", "adjective", "Holding two conflicting feelings or beliefs"),
    ("anachronistic", "adjective", "Belonging to an earlier time"),
    ("anemic", "adjective", "Characterized by a lack of energy or substance"),
    ("angelic", "adjective", "Having or resembling an angel"),
    ("animated", "adjective", "Full of or showing life and vigor"),
    ("apic", "adjective", "Of the topmost petal"),
    ("apocalyptic", "adjective", "Relating to or resembling an apocalypse"),
    ("apocryphal", "adjective", "Of dubious authenticity"),
    ("applaud", "verb", "To show approval or give praise"),
    ("apprehensive", "adjective", "Mentally prepared for an unpleasant situation"),
    ("apprise", "verb", "To inform or notify someone"),
    ("approbation", "noun", "Expressing an affirmative and accepting attitude"),
    ("arboreal", "adjective", "Relating to or resembling a tree"),
    ("arbitrary", "adjective", "Not based on or constrained by reason"),
    ("arch", "adjective", "A raised or distorted eyebrow"),
    ("argot", "adjective", "Of or in the language used by a profession"),
    ("aromatic", "adjective", "Having a pleasant natural odour"),
    ("arrogate", "verb", "To seize or take without justification"),
    ("arsenic", "noun", "A poisonous metal"),
    ("artful", "adjective", "Skillful or adroit in physical matters"),
    ("ascetic", "adjective", "Relating to or characteristic of an ascetic"),
    ("ashen", "adjective", "Of the pale grey color of ashes"),
    ("asphodel", "noun", "A flower"),
    ("asynchronous", "adjective", "Not existing or happening at the same time"),
    ("asymptotic", "adjective", "Concerning a value that tends to infinity"),
    ("asymmetry", "noun", "The absence of symmetry"),
    ("asylum-seeker", "noun", "A person seeking international protection"),
    ("atavistic", "adjective", "Relating to a return to a prior state"),
    ("atheist", "noun", "A person who disbelieves or who insists on proof"),
    ("augury", "noun", "A sign or omen"),
    ("aunt", "noun", "A woman who is an aunt"),
    ("author", "noun", "The creator or compiler of a book"),
    ("autocrat", "noun", "A person with complete control"),
    ("autocratic", "adjective", "Having complete control"),
    ("autocratical", "adjective", "Having complete control"),
    ("autograph", "noun", "A person's handwritten signature"),
    ("automation", "noun", "The use of processes"),
    ("autonomous", "adjective", "Having the freedom to self-govern"),
    ("autopsy", "noun", "A post-mortem examination"),
    ("auto", "adjective", "Of or relating to an automatic mechanism"),
    ("autos", "adjective", "Of or relating to an automatic mechanism"),
    ("auxiliary", "adjective", "Chiefly US: of or relating to an auxiliary"),
    ("avail", "verb", "To help or benefit someone"),
    ("avatar", "noun", "In Hinduism, the incarnation of a deity"),
    ("avenge", "verb", "To inflict hurt or punishment"),
    ("aver", "verb", "To state or assert that something is the case"),
    ("averse", "adjective", "Reluctant to do something"),
    ("avert", "verb", "To turn away or prevent"),
    ("aviary", "noun", "A large cage or enclosure for birds"),
    ("awkward", "adjective", "Making someone feel awkward"),
    ("axiom", "noun", "A statement or proposition from which an argument follows"),
    ("azure", "noun", "A bright blue color"),
    ("backlash", "noun", "A strong negative reaction"),
    ("backroom", "noun", "A room that is to the rear"),
    ("backsliding", "noun", "Relapse into a former state"),
    ("backup", "noun", "A duplicate"),
    ("backward", "adjective", "Directed toward or originating in the past"),
    ("bacterial", "noun", "Bacterial"),
    ("badger", "noun", "A stout animal"),
    ("badge", "noun", "A mark of recognition"),
    ("baffling", "adjective", "Difficult to understand"),
    ("bagged", "verb", "Taken in by a person"),
    ("bailout", "noun", "The provision of help"),
    ("balanced", "adjective", "Marked by psychological equilibrium"),
    ("ballast", "noun", "Compartment"),
    ("balm", "noun", "A soothing or healing agent"),
    ("band", "noun", "A range of positions"),
    ("bandage", "noun", "A piece of gauze"),
    ("bankrupt", "adjective", "Unable to pay debts"),
    ("banner", "noun", "A flag"),
    ("bantering", "adjective", "Cheerful and friendly"),
    ("banter", "verb", "To talk informally"),
    ("bar", "verb", "To prohibit"),
    ("barbecue", "noun", "A method of cooking food"),
    ("bare", "noun", "A short form of bare-knuckled"),
    ("bargain", "noun", "A thing that reduces cost"),
    ("barker", "noun", "A person who stands at the door"),
    ("barn", "noun", "A large farm building"),
    ("barrel", "noun", "A cylindrical container"),
    ("barrier", "noun", "A fence or obstacle"),
]
